### PR TITLE
Automating Repository Generation From Manifests

### PR DESCRIPTION
**Pull request by idavis**
- [x] Generate L4T base Dockerfiles
- [x] Generate L4T base Makefile
- [x] Analyse JetPack 4.3 DLA and other changes
- [x] Generate JetPack Dockerfiles
- [x] Generate JetPack Makefile
- [x] Generate Flash Dockerfiles
- [x] Generate Flash Config Files
- [x] Generate CTI deps Makefiles
- [x] Generate CTI deps Dockerfiles
- [x] Generate Flash CTI Makefiles
- [x] Generate Flash CTI Dockerfiles
- [x] Generate Flash CTI conf files
- [x] Generate Flash Makefiles
- [x] Generate Main Makefiles
- [x] tasks.json - jetpack
- [x] tasks.json - deps
- [x] tasks.json - deepstream 4
- [x] tasks.json - deepstream 4.01
- [x] tasks.json - deepstream 4.1
- [x] tasks.json - cti deps
- [x] tasks.json - cti flash
- [x] tasks.json - driver packs
- [x] tasks.json - samples
- [x] Verify L4T base image linking
- [x] Remove Dependency Builds
- [x] Remove Squashing for JP 4.3
- [x] Fill Out 4.3 DeepStream with all explicit deps

### CODE REVIEW

**Comment by dfacchin** [comment]
Hi @idavis, 
Great PR! Is there a release estimate? 
Thanks.

**Comment by idavis** [comment]
@dfacchin No ETA at the moment. I'm working on it today to see how far I can get.

**Comment by dfacchin** [comment]
@idavis I understand. It's very useful code anyway, thanks a lot for working on it!

**Comment by idavis** [comment]
@dfacchin @eliabruni This should now be able to flash 4.2 through 4.3. I've had to use the overlay in 4.3 for the out of the box flashing as the 4.3 deb package installation requires chrooting that I can't currently get around. That being said, the containers are all deb based for 4.3. It should be in a testable state now while I wrap up the cleanup tasks.

**Comment by eliabruni** [comment]
Awesome @idavis , will try it out asap!

**Pull request merged**
